title: [Isabella's Portfolio]
description: [This page is to showcase what I have learned with the hands-on experience I have gained]
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
